name = "Educenter Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/educenter-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisher’s Educenter theme"
homepage = "https://gethugothemes.com/products/educenter-hugo/"
tags = ['fast', 'modern', 'minimal', 'minimalistic', 'business', 'education']
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = "0.70.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"

[original]
  name = "Educenter"
  homepage = "https://themefisher.com/products/education-template/"
